config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
    belongs_to :user

 end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 include SessionsHelper
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def show
  end

  def edit
  end

  def create
      @picture = current_user.pictures.build(picture_params)
      if params[:back]
        render :new
      else
        if @picture.save
          redirect_to pictures_path, notice: "Post was successfully created."
        else
          render :new
        end
      end
    end

    def update
       if @picture.update(picture_params)
         redirect_to pictures_path, notice:"Edited post！"
       else
         render :edit
       end
     end

     def destroy
     @picture.destroy
     redirect_to pictures_path, notice:"Deleted post!"
   end

   def confirm
     @picture = Picture.new(picture_params)
    end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :content,:image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
   session.delete(:user_id)
   flash[:notice] = 'ログアウトしました'
   redirect_to new_session_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
 def current_user
   @current_user ||= User.find_by(id: session[:user_id])
 end

 def logged_in?
   current_user.present?
 end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<nav class="navbar navbar-dark bg-light fixed-top">
  <span class="navbar-brand mb-0 h1">Facebook Clone</span>

</nav>

<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Bungee&family=Rowdies:wght@700&display=swap" rel="stylesheet">
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class= "top_button">
    <div id="wrapper">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <% if logged_in? %>
        <button type="button" class="btn btn-info"><%= link_to "Profile", user_path(current_user.id) %></button>
        <button type="button" class="btn btn-warning"><%= link_to "Logout", session_path(current_user.id), method: :delete %></button>
      <% else %>
        <button type="button" class="btn btn-info"><%= link_to "Sign up", new_user_path %></button>
        <button type="button" class="btn btn-warning"><%= link_to "Login", new_session_path %></button>
      <% end %>
      <%= yield %>
    <br>
    <footer>
      <p>運営会社  FacebookClone Company</p>
      <p>© 2020-2021 Copyright FacebookClone Company.</p>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, url:confirm_pictures_path, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="signupform">
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div><br>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h2>Send with the following contents.</h2>
    <%= form_with(model: @picture,url: pictures_path, local: true) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image_cache %>
      <p class="showp">Content:<%= @picture.content %></p>
      <p class="showp">
        <strong>Picture:</strong>
        <%= image_tag @picture.image.url if @picture.image? %>
      </p>
      <%= form.submit  "Post" %>
      <%= form.submit "Back", name: 'back' %>
    <% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>


<td><button type="button" class="checkshow"><%= link_to 'Show', @picture %> </button></td>
<td><button type="button" class="checkshow"><%= link_to 'Back', pictures_path %></button></td>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures Index</h1>
<br>
<table class="container">
  <div class="row">
    <% @pictures.each do |picture| %>
      <div class="btn-group btn-group-sm">
        <div class="col-md-12"><h4>Username: <%= picture.user.name %></h4></div>
        <div class="col-md-12 posted_comment"><h5>content：<%= picture.content %></h5></div>
        <div class="col-md-12 posted_picture"><%= image_tag picture.image.url %></div>
        <button type="button" class="btn btn-info"><%= link_to 'Show', picture %></button>
        <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_picture_path(picture) %></button>
        <button type="button" class="btn btn-danger"><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></button>
      </div>
    <% end %>
  </div>
</table>

<br>
<button type="button" class="btn btn-info"><%= link_to 'New Picture', new_picture_path %></button>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 <strong>Image:</strong>
 <%= image_tag @picture.image.url  %>
</p>

<p>
 <strong>Content:</strong>
 <%= @picture.content %>
</p>

<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_picture_path(@picture) %> </button>
<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Back', pictures_path %></button>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<td><button type="button" class="checkshow"><%= link_to 'Show', @user %> </button></td>
<td><button type="button" class="checkshow"><%= link_to 'Back', users_path %></button></td>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<br>
<table class="container">
  <div class="row">
    <% @users.each do |user| %>
      <ul class="btn-group btn-group-sm">
        <li class="col-md-12"><h4>Username: <%= user.name %></h4></li>
        <li class="col-md-12"><h4>Email: <%= user.email %></h4></li>
      </ul>
        <button type="button" class="btn btn-info"><%= link_to 'Show', user %></button>
        <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_user_path(user) %></button>
        <button type="button" class="btn btn-danger"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></button>
      <br>
    <% end %>
  </div>
</table>
<br>

<button type="button" class="btn btn-info new_user"><%= link_to 'New User', new_user_path %></button>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<td><button type="button" class="checkshow"><%= link_to 'Back', users_path %></button></td>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_user_path(@user) %></button>
<button type="button" class="btn btn-info btn-sm"><%= link_to 'Back', users_path %></button>